yaml# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Site settings
title: "Nancy Durkee"
email: "nbdurkee@gmail.com"
description: "Content architect, passionate about trustworthy content and responsible AI."
url: "https://nbdurkee-prog.github.io"
baseurl: "/Portfolio"

twitter_username: username
github_username: nbdurkee-prog
minimal_mistakes_skin: "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: 

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Profile Settings
author:
  name   : "Nancy Durkee"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Content architect, passionate about trustworthy content and responsible AI. Blending my background in writing, education, AI, information architecture, and inclusive content design, I develop contextual knowledge experiences in products, and teach writers how to create semantically structured, trustworthy content."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
toc: true
   toc_label: "On This Page"
   toc_sticky: true
