title: "Nancy Durkee - Writer, Content Architect, Knowledge Strategist"
email: "nbdurkee@gmail.com"
description: "Content architect, passionate about trustworthy content and responsible AI."
url: "https://nbdurkee-prog.github.io"
baseurl: "/Portfolio"

twitter_username: username
github_username: nbdurkee-prog
minimal_mistakes_skin: "sunrise"
search: false

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

permalink: /:title/
paginate: 5
paginate_path: /page:num/
timezone: 

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Nancy Durkee - Writer, Content Architect, Knowledge Strategist"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Content architect, passionate about trustworthy content and responsible AI."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
   
navigation: main
